from models.order import *
import datetime

order1 = Order("Charlie", datetime.date(2021, 11, 3), "1", "Banana", """A gripping biological detective story that uncovers the myth, mystery, and endangered fate of the world's most humble fruit
               To most people, a banana is a banana: a simple yellow fruit. Americans eat more bananas than apples and oranges combined. In others parts of the world, bananas are what keep millions of people alive. But for all its ubiquity, the banana is surprisingly mysterious; nobody knows how bananas evolved or exactly where they originated. Rich cultural lore surrounds the fruit: In ancient translations of the Bible, the 'apple' consumed by Eve is actually a banana (it makes sense, doesn't it?). Entire Central American nations have been said to rise and fall over the banana.
               But the biggest mystery about the banana today is whether it will survive. A seedless fruit with a unique reproductive system, every banana is a genetic duplicate of the next, and therefore susceptible to the same blights. Today's yellow banana, the Cavendish, is increasingly threatened by such a blight -- and there's no cure in sight.
               Banana combines a pop-science journey around the globe, a fascinating tale of an iconic American business enterprise, and a look into the alternately tragic and hilarious banana subculture (one does exist) -- ultimately taking us to the high-tech labs where new bananas are literally being built in test tubes, in a race to save the world's most beloved fruit.""", "https://www.goodreads.com/book/show/1260005.Banana")
order2 = Order("Ana", datetime.date(2021, 11, 1), "3", "Traffic", """Would you be surprised that road rage can be good for society? Or that most crashes happen on sunny, dry days? That our minds can trick us into thinking the next lane is moving faster? Or that you can gauge a nation s driving behavior by its levels of corruption? These are only a few of the remarkable dynamics that Tom Vanderbilt explores in this fascinating tour through the mysteries of the road.
               Based on exhaustive research and interviews with driving experts and traffic officials around the globe, Traffic gets under the hood of the everyday activity of driving to uncover the surprisingly complex web of physical, psychological, and technical factors that explain how traffic works, why we drive the way we do, and what our driving says about us. Vanderbilt examines the perceptual limits and cognitive underpinnings that make us worse drivers than we think we are. He demonstrates why plans to protect pedestrians from cars often lead to more accidents. He shows how roundabouts, which can feel dangerous and chaotic, actually make roads safer and reduce traffic in the bargain. He uncovers who is more likely to honk at whom, and why. He explains why traffic jams form, outlines the unintended consequences of our quest for safety, and even identifies the most common mistake drivers make in parking lots.
               The car has long been a central part of American life; whether we see it as a symbol of freedom or a symptom of sprawl, we define ourselves by what and how we drive. As Vanderbilt shows, driving is a provocatively revealing prism for examining how our minds work and the ways in which we interact with one another. Ultimately, Traffic is about more than driving: it s about human nature. This book will change the way we see ourselves and the world around us. And who knows? It may even make us better drivers.""", "https://www.goodreads.com/book/show/2776527-traffic")

orders_list = [order1, order2]
